! ###################################################################
! Copyright (c) 2013, Marc De Graef/Carnegie Mellon University
! All rights reserved.
!
! Redistribution and use in source and binary forms, with or without modification, are 
! permitted provided that the following conditions are met:
!
!     - Redistributions of source code must retain the above copyright notice, this list 
!        of conditions and the following disclaimer.
!     - Redistributions in binary form must reproduce the above copyright notice, this 
!        list of conditions and the following disclaimer in the documentation and/or 
!        other materials provided with the distribution.
!     - Neither the names of Marc De Graef, Carnegie Mellon University nor the names 
!        of its contributors may be used to endorse or promote products derived from 
!        this software without specific prior written permission.
!
! THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
! AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
! IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
! ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
! LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
! DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
! SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
! CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
! OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE 
! USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
! ###################################################################

!--------------------------------------------------------------------------
! CTEMsoft2013:pgm.f90
!--------------------------------------------------------------------------
!
! MODULE: pgm
!
!> @author Marc De Graef, Carnegie Mellon University
!
!> @brief routine to write an image to a pgm file
!
! 
!> @date 1/5/99   MDG 1.0 original
!
!--------------------------------------------------------------------------
module pgm

use local
use files
use io

IMPLICIT NONE

integer(kind=irg),allocatable   	:: PGM_Image(:,:)
integer(kind=irg)  				:: PGM_nx,PGM_ny

contains

subroutine PGM_Write_File(fname)

character(fnlen) 				:: fname
integer(kind=irg)				:: j, stl

stl = len(trim(fname))
mess = 'Creating PGM file : '//fname(1:stl); call Message("(A)")

open(unit=dataunit,file=trim(fname),status='unknown',action='write',form = 'formatted')
write (unit=dataunit,fmt="(A3)") 'P2 '
write (unit=dataunit,fmt="(A)") '# PGM file generated by CTEMsoft2013'
write (unit=dataunit,fmt="(I5,I5)") PGM_nx,PGM_ny
write (unit=dataunit,fmt="(I5)") maxval(PGM_Image)
do j=PGM_ny,1,-1
  write (unit=dataunit,fmt="(I3)") PGM_Image(1:PGM_nx,j)
end do
close(unit=dataunit,status='keep')

end subroutine PGM_Write_File

end module pgm
