# - Find szlib
# Find the native FORTRANCL_LIB includes and library
#
#  FORTRANCL_INCLUDE_DIR - where to find szlib.h, etc.
#  FORTRANCL_LIBRARIES   - List of libraries when using szlib.
#  FORTRANCL_FOUND       - True if szlib found.
MESSAGE(STATUS "Finding FortranCL")

set(FortranCL_DEBUG 0)


IF (FORTRANCL_INCLUDE_DIR)
  # Already in cache, be silent
  SET(FORTRANCL_LIB_FIND_QUIETLY TRUE)
ENDIF (FORTRANCL_INCLUDE_DIR)

FIND_PATH(FORTRANCL_INCLUDE_DIR cl.mod
  /usr/local/include
  /usr/include
  $ENV{FORTRANCL_INSTALL}/include
)

SET(FORTRANCL_LIB_NAMES fortrancl)
FIND_LIBRARY(FORTRANCL_LIBRARY
  NAMES ${FORTRANCL_LIB_NAMES}
  PATHS /usr/lib /usr/local/lib
  $ENV{FORTRANCL_INSTALL}/lib
)

if(FortranCL_DEBUG)
  MESSAGE(STATUS "FORTRANCL_LIBRARY: ${FORTRANCL_LIBRARY}")
  MESSAGE(STATUS "FORTRANCL_INCLUDE_DIR: ${FORTRANCL_INCLUDE_DIR}")
ENDIF()



IF (FORTRANCL_INCLUDE_DIR AND FORTRANCL_LIBRARY)
   SET(FORTRANCL_FOUND TRUE)
   SET( FORTRANCL_LIBRARIES ${FORTRANCL_LIBRARY} )
ELSE (FORTRANCL_INCLUDE_DIR AND FORTRANCL_LIBRARY)
   SET(FORTRANCL_FOUND FALSE)
   SET( FORTRANCL_LIBRARIES )
ENDIF (FORTRANCL_INCLUDE_DIR AND FORTRANCL_LIBRARY)

IF (FORTRANCL_FOUND)
  MESSAGE(STATUS "Found FORTRANCL_LIB: ${FORTRANCL_LIBRARY}")
ELSE (FORTRANCL_FOUND)
  IF (FORTRANCL_LIB_FIND_REQUIRED)
    MESSAGE(STATUS "Looked for FortranCL libraries named ${FORTRANCL_LIBS_NAMES}.")
    MESSAGE(FATAL_ERROR "Could NOT find z library")
  ENDIF (FORTRANCL_LIB_FIND_REQUIRED)
ENDIF (FORTRANCL_FOUND)

MARK_AS_ADVANCED(
  FORTRANCL_LIBRARY
  FORTRANCL_INCLUDE_DIR
  )
